name = "djb-telegram-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "TWEET_STORE"
id = "e2616f065292418a8a79ef68ed379c6f"

[triggers]
crons = ["30 6,12 * * *"]   # 12:00 PM IST (06:30 UTC) & 6:00 PM IST (12:30 UTC)

[vars]
DJB_USER_ID = "2353131758"
DJB_USERNAME = "DelhiJalBoard"
MAX_TWEETS_PER_CHECK = "20"
